function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Apr-2020 20:39:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.334659090909091 0.815]);
hold(axes1,'on');

% Create text
text('Parent',axes1,'FontSize',14,'Interpreter','latex','String','$0$',...
    'Position',[1.02 0.632120558828558 0]);

% Create text
text('Parent',axes1,'FontSize',14,'Interpreter','latex','String','$0.25$',...
    'Position',[1.02 0.598286023927983 0]);

% Create text
text('Parent',axes1,'FontSize',14,'Interpreter','latex','String','$0.5$',...
    'Position',[1.02 0.564733401606416 0]);

% Create text
text('Parent',axes1,'FontSize',14,'Interpreter','latex','String','$0.75$',...
    'Position',[1.02 0.531857488074989 0]);

% Create text
text('Parent',axes1,'FontSize',14,'Interpreter','latex','String','$1$',...
    'Position',[1.02 0.5 0]);

% Create text
text('Parent',axes1,'HorizontalAlignment','center','FontSize',14,...
    'Interpreter','latex',...
    'String','$C_r$',...
    'Position',[1.04 0.663726586769986 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineStyle','none');
set(plot1(1),'DisplayName','Measured Efficiency','Marker','o',...
    'Color',[0 0 1]);
set(plot1(2),'DisplayName','Theoretical Efficiency','Marker','+',...
    'Color',[0 0 0]);

% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend(axes1,'show');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.570340909090909 0.11 0.334659090909091 0.815]);
hold(axes2,'on');

% Create text
text('Parent',axes2,'FontSize',14,'Interpreter','latex','String','$0$',...
    'Position',[1.02 0.632120558828558 0]);

% Create text
text('Parent',axes2,'FontSize',14,'Interpreter','latex','String','$0.25$',...
    'Position',[1.02 0.598286023927983 0]);

% Create text
text('Parent',axes2,'FontSize',14,'Interpreter','latex','String','$0.5$',...
    'Position',[1.02 0.564733401606416 0]);

% Create text
text('Parent',axes2,'FontSize',14,'Interpreter','latex','String','$0.75$',...
    'Position',[1.02 0.531857488074989 0]);

% Create text
text('Parent',axes2,'FontSize',14,'Interpreter','latex','String','$1$',...
    'Position',[1.02 0.5 0]);

% Create text
text('Parent',axes2,'HorizontalAlignment','center','FontSize',14,...
    'Interpreter','latex',...
    'String','$C_r$',...
    'Position',[1.04 0.663726586769986 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix1,'Parent',axes2,'LineStyle','none');
set(plot2(1),'DisplayName','Measured Efficiency','Marker','o',...
    'Color',[0 0 1]);
set(plot2(2),'DisplayName','Theoretical Efficiency','Marker','+',...
    'Color',[0 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.2 0.3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.16 0.24]);
% Set the remaining axes properties
set(axes2,'XGrid','on','YGrid','on');
% Create legend
legend(axes2,'show');

